### ISSUE TITLE
(STUDENT) View Lecture Section

### ISSUE THREAD

**Issue by Gibdalf** [office-hour-scheduler/ohs#23]
Student UI:
- all info about the lecture section displayed in a header at the top of the page
- below the header, there is a view of all upcoming office hours for that lecture section in the next week (google calendar-like view)
- office hours are displayed as 10-minute slots in the calendar
- clicking on one of these 10-minute slots triggers a dialog which asks if you want to book a meeting in that time slot

**Comment by sakshaat** [comment]
More comments from the Google Doc:
- date picker
- when you choose a date, queries backend for office hours on that date, and list of meetings (or nulls) for those office hours
- displayed as an “agenda view”
- similar component to professor view of lecture section page, but components run vertically instead of horizontally
- each component has 6 rectangles representing the 6
